# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "customer-product"
client_id = "7bf2ae25acb216c05ead3d6ac2464448"
application_url = "https://table-ski-decision-mj.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_customer_merge,write_customer_merge"

[auth]
redirect_urls = [
  "https://table-ski-decision-mj.trycloudflare.com/auth/callback",
  "https://table-ski-decision-mj.trycloudflare.com/auth/shopify/callback",
  "https://table-ski-decision-mj.trycloudflare.com/api/auth/callback",
  "https://table-ski-decision-mj.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rumitsavaliya.myshopify.com"
